name: Continuous Integration and Delivery
on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build & Integração (CI)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Garante a instalação do pylint antes de usá-lo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pylint

      # Executa através do módulo Python para evitar erro 127
      - name: Run Python Lint
        run: python -m pylint main.py || true

  # Job 2: Entrega/Deploy (CD) - Só roda se o 'build' passar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Package application
        run: |
          mkdir deploy_folder
          cp main.py deploy_folder/
          zip -r deploy_package.zip deploy_folder/

      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-app-release
          path: deploy_package.zip